### ISSUE TITLE
Several problems with freecom_lng.* files

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#104]
Hi Jerome,

I was taking a look at the FreeCOM translation in French, and it appears that the freecom_lng.en file is older than the one hosted on [FDOS repository](https://github.com/FDOS/freecom/blob/master/strings/DEFAULT.lng) and is missing at least two strings (labels: :TEXT_MSG_VER_DEVELOPERS and :TEXT_ERROR_EXE_CORRUPT). No idea if there's more, but I think it's worth taking a look into.

Also, the e-mail address for bug reports needs to be updated in various translations and the "Current maintainer; Steffen Kaiser mailto:freecom@freedos.org." sentence needs to be removed. Finally, even the newer file on the FDOS repository needs to update the FreeCOM homepage which currently is https://github.com/FDOS/freecom and not http://freedos.sourceforge.net/freecom anymore; and the copyright years ((C) 1994-2005 ??) may need to be updated as well.

**Comment by shidel** [comment]
Well, I did a back port from the FDOS repository. Also, @andrewbird has mentioned he preferred a different file naming scheme. So, I renamed some stuff. Since the ones in FDOS have been updated recently, I mostly just used those. However, the Swedish version on FD-NLS is newer than that in FDOS. So, I made certain to preserve the new one.

**Comment by shidel** [comment]
Can this issue be closed?

**Comment by cardpuncher** [comment]
On 4.02.2022 12:06, shidel wrote:
> Can this issue be closed?

I think it can be closed, indeed. You already pinged @andrewbird and the 
only remaining stuff is updating the FreeCOM repository address and the 
copyright years. Maybe it would be better if I filed an issue on the 
FreeCOM GitHub repository regarding this?

**Comment by andrewbird** [comment]
>Well, I did a back port from the FDOS repository. Also, @andrewbird has mentioned he preferred a different file naming scheme. So, I renamed some stuff.

Yes, thanks for that it made the import to Freecom considerably easier having matching filenames.

>  Can this issue be closed?

Fine by me, I raised a PR and it has been merged https://github.com/FDOS/freecom/pull/72#event-6009058743

**Comment by shidel** [comment]
> Yes, thanks for that it made the import to Freecom considerably easier having matching filenames.

Your welcome. :-)
