### ISSUE TITLE
Various translations and updated NLS files

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#12]
Attached archive contains translations in French and Turkish for various files, and some files from freedoslocal.sf.net that I have updated, following Mateusz's advice to shorten the lines. All of them have both code page and UTF-8 versions. There are also files for FreeCOM with a few less typos, hoping that you will make a release containing them (if so, please don't forget the Serbian/Yougoslavian and Croatian locales, see <https://github.com/FDOS/freecom/commit/b35c579d676b23aa22fa55dc03e887a84aed5b11> and <https://github.com/FDOS/freecom/commit/9eec401e952f23b4589774e1b2ba9ee0465c35d5>).

You can also find package lists in csv format, hopefully the RBE won't return errors on them (I used your bash script, it's awesome). Only UTF-8 for these ones.

AFAIK, the only translation I still need to do is for pgme. If I forgot something, feel free to yell at me (it's kind of funny and messy to follow commits to find stuff to translate from what others have submitted).

Best regards.

[freedos_translations.zip](https://github.com/shidel/fd-nls/files/4728141/freedos_translations.zip)

**Comment by shidel** [comment]
I'll take a look. 

Mateusz's has wanted the **Description** field to be rather short. I think 80 characters or less. I understand his reasoning and mostly agree. This is why the **Summary** field was born. It is not a required field. But, it is available to provide a means of giving much more detailed information. It can be used to summarize a program in a few sentences or paragraphs. The [online repo's](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/latest/pkg-html/index.html) display both fields when present. **FDIMPLES** and uses both as well, preferring the **Summary** field in some places and **Description** in others.

**Comment by cardpuncher** [comment]
On 4.06.2020 11:51, shidel wrote:
> I'll take a look.

Thank you.

> Mateusz's has wanted the *Description* field to be rather short (...) 

Thanks for your explanation, but I meant the body of French translations
of some programs like fdnpkg.fr. I had asked in the mailing-list whether
the 80 character limit was important
(<https://sourceforge.net/p/freedos/mailman/message/37014346/>) and you
told me to check with Mateusz, which I did. He advised me to reword
phrases and bend the language a little bit when necessary, hence the
files in the updated_files_from_freedoslocal subdirectory.

**Comment by shidel** [comment]
> Thanks for your explanation, but I meant the body of French translations of some programs like fdnpkg.fr. I had asked in the mailing-list whether the 80 character limit was important (<https://sourceforge.net/p/freedos/mailman/message/37014346/>) and you told me to check with Mateusz, which I did. He advised me to reword phrases and bend the language a little bit when necessary, hence the files in the updated_files_from_freedoslocal subdirectory.

Ok. I recall that message. You were referring to the in-program translations for messages that the program itself used for multi-language. For example, if when fdnpkg prints a message like "Installing xyz package now" etc. 

Since you mentioned "package lists" in the first message of this thread, I thought you were referring to shortening those Descriptions. My mistake. :-)

**Comment by shidel** [comment]
Sorry, I've been rather occupied lately and just now got around to adding the translations you provided in that zip archive for various packages and the listing files.

The RBE and the status.sh use very similar code to parse LSM files. I've only ran the status.sh tool on them. The Turkish one generated no issues at all. The French had a couple extra empty fields and the status.sh script complained. But since the checksum fields were aligned, it did accept them. However, the French version is still missing the all of "new" packages.

**Comment by shidel** [comment]
Hi, thanks again for the updates.

You may consider taking a look at the [report.txt](https://github.com/shidel/fd-nls/blob/master/report.txt) file. While not perfect and can still use more work, it may assist in finding files that need translated or updated. Please note, if a program contains any translations for a language, it will appear in the list for that language even if that program could have additional files that may not exist. For example: **more** contains basic NLS translations for **TR**, however there is no **TR** translation for the more help screen.

**Comment by cardpuncher** [comment]
On 25.06.2020 15:17, shidel wrote:
> Hi, thanks again for the updates.
> 
> You may consider taking a look at the report.txt
> <https://github.com/shidel/fd-nls/blob/master/report.txt> file. 

Hello Jerome,

Sorry for the very long delay, but I'm back to translating FreeDOS stuff
again. The attached zip archive contains several new translations, both
in UTF-8 and relevant code pages thanks to your report.txt file that
helped greatly.

A few remarks about the translations:
The help file for TREE mentions a link to download cats, namely
<http://www.freedos.org/jhall/cats>, but it's broken. An update would be
nice.

I noticed slight differences between tree and pdtree which seems to be
more recent according to the copyright year (and it has additional
strings). Hope that's normal.

As for Blocek, the translated version mentions 1.4 whereas 1.62 has been
released, see <http://laaca.sweb.cz/>. A couple of days ago I dropped a
message to the e-mail address I found in the l10n file but haven't
gotten a reply yet.

Regarding wget, as I'm lazy I shamelessly stole many strings from the
GNU/Linux version, I hope that's not a problem.

Finally, regarding TEE, the help file is in HTML and apparently part of
an older version of the HTML help. In fact, I translated all the HTML
Help of FreeDOS in French and Wilhelm has a copy, you should soon
receive it after he makes some final corrections. So I translated the
older version and added the current one, feel free to pick the one you
prefer. As Lorenzo del Toro Saravia translated all the help files in
Spanish, and if you prefer the current version, you can just add the
Spanish version as well ;) Also, please tell me which one I should
translate in Turkish.

Phew, that's all for now. Feel free to update the report.txt file, I'll
take a look at what's left to translate.

**Comment by cardpuncher** [comment]
Argh, the e-mail attachment wasn't taken into account by GitHub. Here's the zip archive:
[freedos-fr-tr.zip](https://github.com/shidel/fd-nls/files/5372334/freedos-fr-tr.zip)

**Comment by shidel** [comment]
Hi, everything is looking pretty good. Updated the reports. At a glance I only see  FR/TR translations missing for DOSLFN, MODE and V8POWER. 
I also regenerated the reports for the [package descriptions](https://github.com/shidel/fd-nls/tree/master/packages) used by FDIMPLES (and eventually the online repositories). There are 3 packages in without TR descriptions and a lot of ones missing from the FR CSV.

**Comment by shidel** [comment]
I messaged Jim about about the broken cats link. He created a [landing page](http://www.freedos.org/jhall/cats/) there to redirect to the current versions.

**Comment by cardpuncher** [comment]
Thanks for the landing page, it looks good. I finished translating STAMP and the package descriptions in French and Turkish, they're attached. Some remarks in no particular order:

https://github.com/shidel/fd-nls/blob/master/packages/readme.md should maybe mention that one needs to create a directory for the target language within the one containing the status.sh script, like /fr or /tr. Took me some time to figure that out after my "vacations".

I got a reply from Blocek's author who wondered why I translated the old 1.4 dating back to 2013 and asked me to translate the current version (1.62), which I did. Waiting for a message from him again.

Please forget about the newer version of TEE HTML help files or even better, remove it. I stupidly forgot absolute paths in it, the see also links are pointless in this context and so on. Let's just keep the original version. I attached the Turkish version.

Thank you :)

**Comment by cardpuncher** [comment]
For some reason, attaching the archive didn't work with Pale Moon, so here it is, with Firefox this time. Sorry about that.

[STAMP_TEE_and_packages.zip](https://github.com/shidel/fd-nls/files/5461202/STAMP_TEE_and_packages.zip)

**Comment by shidel** [comment]
Sorry it took so long for me to get around to these, I've been wrapped up with **_IRL_** stuff.  

It was really awesome to watch the **status.sh** script process the languages. German,  complaint, complaint, complaint... FR & TR, running... Not one single gripe. :-)
