### ISSUE TITLE
Norwegian code page should probably be 865, not 857 which is for Turkish

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#130]
Hi Jerome,

I finally got around to having fun with FreeDOS again, sorry for the long hiatus. I was trying to get the FD-NLS app to display Turkish characters properly and I think everything is fine except for three characters: positions 231, 240 (soft hyphen) and 242 for which I'll need your help. Anyway, I was about to send a pull request but saw that with commit b1501c2ffe0801814d639cac06f302586686e9e8 you added Norwegian with IBM code page 857 whereas that's the code page for Turkish.

According to <a href="https://en.wikipedia.org/wiki/Code_page_865">Wikipedia</a> Norwegian should probably use CP 865. If that's correct, you may need to adapt the repo so that I can send my PR without overwriting anything.

**Comment by shidel** [comment]
Hi, I changed the CP for Norwegian to 857. And added the missing TR for the settings for Turkish. 

Now, for the 3 problem Turkish characters. Two are missing from CP font and the other may be wrong. So... Open the font file in DOS using imgedit.

![Screen Shot 2022-05-30 at 10 42 48 AM](https://user-images.githubusercontent.com/10198034/171016304-fef08a81-18d1-4c84-a62a-58fed48e1928.png)

Use the arrow keys to navigate to the first missing character and then the mouse to edit it.

![Screen Shot 2022-05-30 at 10 47 42 AM](https://user-images.githubusercontent.com/10198034/171016536-72c57e28-9f87-4811-9aad-68804d61bb9b.png)

Repeat for each bad DOS character. Once done, use the menu to save the font.

Now head back over to the FD-NLS Desktop app. Go to settings, languages, Turkish and click the Codepage Edit button. 
![Screen Shot 2022-05-30 at 10 54 56 AM](https://user-images.githubusercontent.com/10198034/171017902-e88eff5f-7157-44cb-be58-4c8308083542.png)


The DOS versions will should be correct. You will then need to enter the UTF-8 version. Once done, just click OK. 

Be sure to add the updated font fonts/857.fnt and the codepages/857.xml to your commit.

**Comment by cardpuncher** [comment]
Thank you for the detailed explanation, I'm on it. In the meantime, you may need to fix the file name of [857.xml](https://github.com/shidel/fd-nls/blob/master/fd-nls/codepages/857.xml) on https://github.com/shidel/fd-nls/tree/master/fd-nls/codepages.

**Comment by shidel** [comment]
Forgot to add Codepage 865 xml file. Just did that. I think they are correct now. But, those bad characters for the Turkish font will still need corrected.
