### ISSUE TITLE
Various license problems in the package list

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#137]
Hi,

While updating the package list with the FD-NLS app and now that the license field is translatable, I noticed several problems. Here's a non exhaustive list as a reminder:
- Many packages have a license field that indicates "Free w/sources". In such a case, what's the meaning of free? At no cost, gratis or free as in freedom? In English it's the same word but not in other languages, and it matters when it comes to translations so using something else than free for proprietary programs would be nice ("gratis" maybe?). It's been burdensome to check in the source files and even then in some cases things aren't clear. Consider XMGR for instance, on https://gitlab.com/FreeDOS/drivers/xmgr/-/blob/master/DOC/XMGR/README.TXT one can read "XMGR is offered at no cost, "as is", "use at your own risk" and with NO warranties, not even the implied warranty of FITNESS for any particular purpose, nor the implied warranty of MERCHANTABILITY!". Modifications aren't explicitly allowed.
- There are several instances of programs that are explicitly non-free (Freeware, CC BY-ND, source code not available and so on). IMHO it would be nice to either remove them, or at least move them to another repository. It's not like those would prefer to use proprietary stuff are lacking alternatives (SvarDOS springs to mind).
- In almost all cases, the license is indicated without stating if following versions are allowed. IMHO it would be better to indicate "GNU General Public License, Version 3+" (or something like any later version) instead of just "Version 3".
- There's a mistake for the license of the GPLv2 document. Its license is not GPLv2 but verbatim copying.
- As for LAME, its license should be LGPL v2.1+ (as indicated for instance by the header of say <https://sourceforge.net/p/lame/svn/HEAD/tree/trunk/lame/libmp3lame/VbrTag.c> and not GPLv2.
- FreeDOS Password indicates GPLv2.1+ as its license, even in its source code, the problem is that such a version never existed in the first place. Maybe it should have been LGPL? Should I ping Mateusz about that?

Boring stuff, indeed... :)

**Comment by shidel** [comment]
Oh since it is NOT editable in FD-NLS (at present), you should provide me with a list of exactly which packages you have seen with incorrect licenses. That way I can correct their metadata.

**Comment by cardpuncher** [comment]
On 1.07.2022 17:53, shidel wrote:
>       * Many packages have a license field that indicates "Free
>         w/sources". In such a case, what's the meaning of free? At no
>         cost, gratis or free as in freedom?
> 
> Free of charge... No Cost.

Crap. I translated it as free as in freedom. I'll need to correct these 
entries. A new PR should arrive next week. I would suggest to use 
something else in English in the future, like "gratis" or "free of 
charge" to avoid confusion.

> At some point in the future when I get motivated and have the time, 
> FDIMPLES will get networking and provide support to pull packages from 
> multiple online repositories.
> 
> Eventually, the tools that combine them should include the SOURCE repo. 
> And, the FD-NLS app should identify where it is for and provide the 
> ability to Filter them based on the repository.

That would be great, thanks!

>       * In almost all cases, the license is indicated without stating if
>         following versions are allowed. IMHO it would be better to
>         indicate "GNU General Public License, Version 3+" (or something
>         like any later version) instead of just "Version 3".
> 
> 
> I would stick with exactly what the license says. If it is says "Version 
> 2" use that. Or if it says "2 or later", use it. We should avoid trying 
> to make assumptions.

OK, that's what I did so we're (almost) in the clear on that front. What 
I was merely suggesting is that for many programs, the file headers say 
something like "
  * This library is free software; you can redistribute it and/or
  * modify it under the terms of the GNU Lesser General Public
  * License as published by the Free Software Foundation; either
  * version 2 of the License, or _(at your option) any later version_."
(emphasis mine) so this could be taken into account. Instead, in the 
package list it seems like only the license document is considered 
without taking a look at the source code file headers, so the later 
version thingy is left out in nearly all cases.

>       * There's a mistake for the license of the GPLv2 document. Its
>         license is not GPLv2 but verbatim copying.
> 
> I don't understand what you are referring to.

Sorry for not being clear. I was referring to the line 176 of the csv 
file which is an entry for the GNU GPLv2 text. And its copying policy 
cell states that its license is GPLv2 whereas it should have been 
verbatim copying as the GNU GPL license text itself states that 
"Everyone is permitted to copy and distribute verbatim copies of this 
license document, but changing it is not allowed."

id	title	description	summary	keywords	platforms	copying-policy	sha	
gplv2	GPLv2 Document	GNU General Public License, Version 2		freedos, 
gpl	DOS	GNU General Public License, Version 2 
fe4cca5d84b5c6b6355bb2c3bfc28970d773737ba48fdddc4e0be50b4ad2a937						

> [LAME] will need check and/or fixed. It is possible that either the 
> version we have is listed with the wrong license. Or possible, it is 
> multiple licenses. Or maybe, it could have changed licenses in later 
> versions.

I checked 
<https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/sound/lame.zip> 
and it looks like it's LGPL 2.0+. They seem to have updated the license 
later to LGPL 2.1+. In all cases, it's not GPLv2.


>       * FreeDOS Password indicates GPLv2.1+ as its license, even in its
>         source code, the problem is that such a version never existed in
>         the first place. Maybe it should have been LGPL? Should I ping
>         Mateusz about that?
> 
> Don't want to assume. We should get clarification from Mateusz.

OK, I'll send him a word and post an update when I receive an answer.

> Oh since it is NOT editable in FD-NLS (at present), you should provide
> me with a list of exactly which packages you have seen with incorrect 
> licenses. That way I can correct their metadata.

GPLv2, LAME and password (for which I'll send a message to Mateusz).

**Comment by cardpuncher** [comment]
On 1.07.2022 17:53, shidel wrote:
> 
>       * FreeDOS Password indicates GPLv2.1+ as its license, even in its
>         source code, the problem is that such a version never existed in
>         the first place. Maybe it should have been LGPL? Should I ping
>         Mateusz about that?
> 
> Don't want to assume. We should get clarification from Mateusz.

I got a reply from Mateusz. Hey says that "the FoxCubs library is LGPL 
2.1-licensed (although curiously the license introduction appears 
mistyped), while the FD Password program itself is GPL 2+."

The FoxCubs.pas file has a mistake in the license header (the "Lesser" 
word appears to be forgotten), and the Password.pas file is indeed under 
GPLv2+.

Hope this clarifies the license situation of this program.

**Comment by shidel** [comment]
I think this can be closed now.

**Comment by shidel** [comment]
> OK for me. Some stuff isn't yet updated in the csv file but it can
certainly be done later.

Thats actually a multi-fold issue. 

First, the CSV (English version) is created from the CSV listing files generated by the repositories at [official ibiblio](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/latest/) and my [personal (larger)](https://fd.lod.bz/repos/current/). Those repos generate their listing.csv file based on the zip packages in their repos. The MASTER CSV will use IBIBLIO's version when present and falls back to FD.LOD.BZ  version when needed. Those packages need changed to change the english information. 

However, this has nothing to do with the FreeDOS release anymore. All packages in the release come directly from the [FreeDOS GitLab Archive](https://gitlab.com/FreeDOS). Those packages contain the latest English information. I also run automated routines that pull translation updates from FD-NLS into those projects. Those are done individually and occasionally on mass.

Eventually, a couple other things will need to happen. First, the MASTER.CSV will need to be setup to prefer the GitLab Archive over both IBIBLIO and FD.LOD.BZ. That will not be a simple matter. There is no CSV file there and everything is spread out over multiple-projects in metadata files. At some point, a method of updating the packages in the repos when the source projects in the archive are modified. But there are numerous technical issues the complicate that. For example, the network package updater will not update packages with the same version number. 

In the meantime, here is what it boils down to. Items in the master CSV file are most likely only updated when the version of a package get's updated.
