### ISSUE TITLE
Share got kitten support

### ISSUE THREAD

**Issue by andrewbird** [shidel/fd-nls#163]
Hi, I added kitten support to SHARE https://github.com/FDOS/share/blob/master/nls/share.en. It's not yet in a release, but it might be nice if people were to add translations for when one comes. Thanks.

**Comment by shidel** [comment]
@andrewbird, I added it. Whenever the new versions is ready, we will need to add it to the GitLab FreeDOS archive under an unstable branch. That way it will get included it the following interim OS build.

**Comment by andrewbird** [comment]
Cool thanks. Should I close this or leave it open to attract more translations?

**Comment by shidel** [comment]
I think we can go ahead and close it. Other than @cardpuncher and Wilhelm, most contributors only submit a couple things.
