### ISSUE TITLE
Conversion problems

### ISSUE THREAD

**Issue by andrewbird** [shidel/fd-nls#165]
I ran my UTF-8 -> codepage checker on current fd-nls today and found the following problems

ptBR: # encoding problems
   exe2bin
   fdisk
   flashrom

no: # encoding problems
   xcopy

de:  # string mismatch between UTF-8 text and encoded
  fdtui

**Comment by shidel** [comment]
Hi, 

> ptBR: # encoding problems exe2bin fdisk flashrom

Looking at them in a text editor, it appears that both versions were in UTF-8 format. So, exported the CODEPAGE versions using Portuguese. Hopefully, that is the proper code page. The text editor does not have many DOS code pages and does not provide their numbers. 

> no: # encoding problems xcopy

This seems to be the exact opposite problem. Both files appear to probably be in code page format. However, the editor I have does not include that code page. So, nothing I can do about it for now.

> de: # string mismatch between UTF-8 text and encoded fdtui

Looking at it. It appears the only difference is the copyright string and header comments. I updated the years in the copyright string for the UTF-8 version.

**Comment by andrewbird** [comment]
Closed by #166
