### ISSUE TITLE
Workflow Fails validation

### ISSUE THREAD

**Issue by shidel** [shidel/fd-nls#181]
Hi @andrewbird,

Over the last few months, the [validation workflow](https://github.com/shidel/fd-nls/blob/master/.github/workflows/ci-build.yml) has been failing. Might want to take a look at it. 

:-)

**Comment by andrewbird** [comment]
Sure, it's because some translations have been merged that have both code page specific and Utf-8 files and they are not identical text (when converted).

**Comment by shidel** [comment]
Looking at the run history, the first failure was [run](https://github.com/shidel/fd-nls/actions/runs/6042333037) from about 3 months back. Where it appears to have failed while processing a HELP document for DOSLFN at https://github.com/shidel/fd-nls/actions/runs/6042333037/job/16397212744#step:3:1717 . 

Also, there were two different FR UTF-8 files. A *-UTF-8 (Sept) and a *.UTF-8 (Dec).
I deleted the older one. 
Then, exported the newer in a DOS compatible codepage. 
Validation succeeded. 

So, looks like it's good now. :-)

**Comment by andrewbird** [comment]
Yes the files look like they match now, good stuff.
