### ISSUE TITLE
Various translations in French & Turkish

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#19]
Hey Jerome,

Here comes the French translation of the help files for V8POWER in IBM CP 850. Have fun :)

[V8POWER_help_fr.zip](https://github.com/shidel/fd-nls/files/5898664/V8POWER_help_fr.zip)

**Comment by cardpuncher** [comment]
Well, that one was quick and easy. French & Turkish translations for runtime are attached.

[runtime-fr-tr.zip](https://github.com/shidel/fd-nls/files/5898685/runtime-fr-tr.zip)

**Comment by shidel** [comment]
Thank you. :-)
