### ISSUE TITLE
Turkish help files for V8Power Tools and two corrected files in French

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#20]
Hey Jerome,

I'm attaching Turkish help files for V8Power Tools and two files in French in which I corrected stupid mistakes (I had translated color labels, there was a couple of translation mistakes and so on).

@bitigchi Feel free to check the translations and improve them :-)

[help.zip](https://github.com/shidel/fd-nls/files/6014949/help.zip)

Now I can start working on PGME.

**Comment by bitigchi** [comment]
@cardpuncher, this is great! Thanks for all your labour. The translations look fine to me, only two phrases caught my attention:

Batch: Toplu iş
Max: En çok

Other than that they look great. There are a couple of phrases that can be substituted to a more "Turkish" variant, once this is merged I'll have a go at it with your permission.

**Comment by cardpuncher** [comment]
Thank you. "max" in vprogres.tr seemed to be a variable so I left it as it is, but after they're merged, of course you can fix my mistakes. Let's wait for Jerome to show up :)

**Comment by bitigchi** [comment]
To be clear, there are no mistakes, I'm just obsessed with using pure Turkish. :)

**Comment by shidel** [comment]
> Thank you. "max" in vprogres.tr seemed to be a variable so I left it as it is, but after they're merged, of course you can fix my mistakes. Let's wait for Jerome to show up :)

First, thank you for the Turkish translations. :-)

You are correct. OF **max** is a variable. It can be used to let the utility do the math and figure out the actual percentage. Things like **_5 OF 10_**  (50%), **_6 of 12_** (50%), **_8 of 50_** (16%) and so on.

**Comment by shidel** [comment]
> Now I can start working on PGME.

:-)
