### ISSUE TITLE
An attempt to silence some warnings in reports.txt for French & Turkish

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#21]
Hi Jerome,

Since I'm still procrastinating about PGME :P I took a look at the failing checks in reports.txt (you may want to update that file, btw). Files in the attached archive _should_ silence several warnings. To summarize:

- 1.1: was missing at the beginning of the corresponding line in fc.fr, so I just added it.

- Updated remark lines in FDIMPLES.FR and TR at the top of the translation file. That was the only change, the error message will hopefully be silenced.

- fdpkg.fr was in fact the translation for fdnpkg hence so many failed checks. Sorry for that. The correct file is attached.

- fdtui has a new version at https://github.com/ercanersoy/FDTUI/ which should fix the failing checks.

- "htmlhelp: de, en, es, fr, it, nl, pl, sk, sl, sv, tr, de?, es?, fr?" : didn't quite get that, fr is mentioned twice?

- tree: I updated the translation file, the error message should be silenced now.

[fix_failing_checks.zip](https://github.com/shidel/fd-nls/files/6016404/fix_failing_checks.zip)

**Comment by shidel** [comment]
htmlhelp has a "odd" structure compared to everything else. It along with a couple others (like command.com) aren't fully supported by the testing scripts. I don't feel it is worth the effort to write custom testing code for each of those unusual programs.
