### ISSUE TITLE
French & Turkish translations the help files of choice and fc

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#22]
Hi,

I'm attaching French & Turkish translations for the help files of choice and fc. I also included the help file of choice in English because it includes a correction to Jim's e-mail address (.org tld instead of .net). 

All the best.

[choice_and_fc_help.zip](https://github.com/shidel/fd-nls/files/6020237/choice_and_fc_help.zip)

**Comment by shidel** [comment]
Thanks :-)
