### ISSUE TITLE
Question about the help files of DOSLFN and MODE

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#24]
Hey Jerome,

I was about to translate <https://github.com/shidel/fd-nls/blob/master/doslfn/help/doslfn.en> and <https://github.com/shidel/fd-nls/blob/master/mode/help/mode.en> but I couldn't find where these files are actually used. <code>doslfn /?</code> doesn't make use of the help file mentioned above in FreeDOS 1.3 RC3 and the same also goes for <code>mode /?</code> ; and <code>help doslfn</code> or <code>help mode</code> will open the HTML help, so I was wondering whether it made sense to translate them.

Besides, IIRC FreeDOS now uses MODE from Eric Auer, not the one from the author of the file above.

So if you say the translation of these files are useful then I will happily get back to work, otherwise I think I'm going to kill some people on my favorite MMORPG :)

**Comment by shidel** [comment]
Hi,

Unfortunately, I don't know which programs use or more importantly don't use the translations in the help directory. For the ones that don't use them, they still may be useful in the future when/if those programs get updated. But again, translating all of those may be a wast of time. Whatever you decide. 

When I mentioned translating the help, I was referring to the [HTML help files](https://github.com/shidel/fd-nls/tree/master/htmlhelp/help).  There is no Turkish version of those. :-)



On a side note, the [package lists](https://github.com/shidel/fd-nls/tree/master/packages) CSV files have had about a dozen or so additions. So, the FR & TR translations are missing a couple entries. :-)
