### ISSUE TITLE
Suggested corrections after playing a bit with 1.3RC4

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#26]
Hey Jerome,

I have made a cursory check of the translations in 1.3RC4 and found several things to correct. A zip archive containing the corrected files is attached. A quick summary of the changes follows:

- diskcopy, fdnpkg, md5sum and mem were encoded in UTF-8. CP850 versions are now in the archive to make things easier for you, along with UTF-8 files. I really don't know how I missed that.
- fdnpkg was updated with new strings (3 in total IIRC) that were not included in the fdnpkg.en file on this repository, thus this wasn't mentioned in reports.txt. You may find the latest version on <https://sourceforge.net/p/fdnpkg/code/184/tree/trunk/nls/fdnpkg.en>. So I updated French and Turkish translations.
- Typo fixes and slight adjustments in xcopy.fr, localize.fr, tree.fr and FDSETUP.DEF in French.

Also, a couple of remarks:

- After installing FreeDOS 1.3RC4, in C:\FDOS\NLS, several translations are missing for STAMP, including French and Turkish ones.
- Again, for some tools like APPEND, the /? option returns the help file in English despite the fact that I chose French (or Turkish) during the installation process. Is that normal?

Finally, thank you for releasing all the translations as an archive. Using grep on the extracted tarball was a joy :)

[corrections.zip](https://github.com/shidel/fd-nls/files/6445884/corrections.zip)

**Comment by shidel** [comment]
@cardpuncher, I just wanted to let you know that I've been rather occupied the last couple weeks. I don't know how soon it will be until I look into these. I'll get to it eventually. I just wanted to let you know I'm not ignoring you. :-)

**Comment by shidel** [comment]
Hi, I think all these have been integrated. You may want to double check them. Especially, the one for FDI. During a test run of an RC5 Build, I found that TR & FR were slightly broken and fixed them. Basically, they were missing an [important line](https://github.com/shidel/fd-nls/blob/112bed23faf97ed5f8ef0442f83e7c4b018048fb/fdi/language/tr/FDSETUP.DEF#L18). It is a macro that the RBE uses to generate a special entry that is the entire list of languages. That entry is used by the installer when the entire list changes languages to help improve performance. Anyhow, I used FreeDOS edit to stick it back in and all seemed good to me. 

As for the ones that were in FD-NLS, but didn't show up in RC4. The RBE handles it all differently now. So, they should be good in RC5. (Which is basically done and only a couple days away from release now)

The you've got a few minutes, please double check these and let me know if I can close this issue.
:-)

**Comment by shidel** [comment]
As for STAMP, actually those couple files installed into the NLS directory should not exist. After looking at that, I don't think Stamp does NLS. The translated files for STAMP are just documents and go into the %DOSDIR%\DOC\STAMP directory. I'll fix the package and remove the erroneous files from the NLS dir. :-)

**Comment by cardpuncher** [comment]
On 5.12.2021 14:58, shidel wrote:

> As for the ones that were in FD-NLS, but didn't show up in RC4. The RBE
> handles it all differently now. So, they should be good in RC5. (Which
> is basically done and only a couple days away from release now)

Good news, but weren't we going to wait for a new kernel and FreeCOM
release?	

> The you've got a few minutes, please double check these and let me know
> if I can close this issue.
> :-)

Yes, I think you've incorporated all the files in the archive. As for my
remarks, well, looking forward to testing them in the new RC. :-)

**Comment by shidel** [comment]
> Good news, but weren't we going to wait for a new kernel and FreeCOM release?

We have them. For RC4, I think we had 2042 and 0.84-pre7. Now for RC5, its 2043 and .085a. I just don't think there were any announcements made that they were available. Or at least, I didn't notice any the time or missed seeing them. But eventually, I noticed they were available. 

> Yes, I think you've incorporated all the files in the archive. As for my remarks, well, looking forward to testing them in the new RC. :-)

Alright, I close this in a bit then. Not like we cannot open a new one. :-)
