### ISSUE TITLE
Package Descriptions

### ISSUE THREAD

**Issue by shidel** [shidel/fd-nls#39]
Hi @cardpuncher ,

Not sure if you noticed this... 

But, the [package description listing files](https://github.com/shidel/fd-nls/tree/master/packages) for FR & TR are missing a couple translations. 

Only 4 of them are missing. Which is really good. 

Those 4 are fairly new packages. 

Anyhow, I just thought I'd point it out in case you hadn't noticed. :-)

**Comment by cardpuncher** [comment]
Hey Jerome,

Thank you for pinging me on this, indeed, I completely missed that there were updated packages. Needless to say, if it happens again feel free to yell at me :-)

Updated csv files are attached below.

[csv-fr-tr.zip](https://github.com/shidel/fd-nls/files/6912556/csv-fr-tr.zip)

**Comment by shidel** [comment]
Thanks for the update :-)
