### ISSUE TITLE
Slightly improved French translations

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#4]
Attached are improved French translations for all the tools listed at <http://freedoslocal.sf.net/> except for FreeCOM files, already on <https://github.com/FDOS/freecom/issues/25>. A spellchecker and Grammalecte caught most of the mistakes. The codepage is 850 and Windows line endings are used.

Looking forward to testing these in the next 1.3 RC.

[french.zip](https://github.com/shidel/fd-nls/files/4646010/french.zip)

**Comment by shidel** [comment]
Thanks
