### ISSUE TITLE
Incorrect French characters in readme.

### ISSUE THREAD

**Issue by shidel** [shidel/fd-nls#50]
Hi @cardpuncher, 

A bug report was submitted on [sourceforge](https://sourceforge.net/p/pgme/tickets/2/) regarding the PGME french documentation. I think this is a character that is not in the correct codepage. If your not too busy, I hope I can get you to take a look at it.

Thank you, :-)

**Comment by cardpuncher** [comment]
Reading the ticket on SourceForge, I think we can safely close this issue :)

**Comment by shidel** [comment]
Ok, thanks.
