### ISSUE TITLE
New Readme, meh

### ISSUE THREAD

**Issue by shidel** [shidel/fd-nls#52]
Hi @cardpuncher,

Per your request on the online get-together, the report utility (formerly checkup.sh), now creates also updates the README.md and creates a README.html. Unfortunately, it cannot do any color stuff in markdown and GitHub turns html into text. 

But, on the bright side. when you checkout / pull the latest version. The HTML can be viewed locally.

As for the Markdown version, I tried a couple things. Overall, the only thing that worked and was fairly easy to read at a glance was to break it down into separate tables. But, that makes the DOC fairly long and I don't like the way it looks. I may end up just limiting that version to Missing only translations or excluding the all that information from the markdown version.

**Comment by cardpuncher** [comment]
On 19.08.2021 22:27, shidel wrote:
> Hi @cardpuncher <https://github.com/cardpuncher>,
> 
> Per your request on the online get-together, the report utility
> (formerly checkup.sh), now creates also updates the README.md and
> creates a README.html. Unfortunately, it cannot do any color stuff in
> markdown and GitHub turns html into text.
> 
> But, on the bright side. when you checkout / pull the latest version.
> The HTML can be viewed locally.

Hey Jerome,

Thanks for taking care of this, the HTML file looks great locally.
Definitely not meh! As a mere suggestion, perhaps it could be put on a
"real" website via <https://pages.github.com/> optionally along with
links to the translation files? This would make a great welcome page for
the FD-NLS project, maybe with some information about code pages and
such to get newbie translators started (I could write a short "tutorial"
based on my experience). That way, it wouldn't be necessary to work on
the markdown version at the same time.

(I know, it's easier said than done and that means moar work for you,
but hey...)

**Comment by shidel** [comment]
Well, I looked into it briefly. Without doing a lot of extra stuff, it pretty much converts the readme.md to html and displays it. So, the landing page would be just that file. On the plus side, it will show HTML files in the repository. So, I turned it on and updated the README with a link to the report and it works. [https://shidel.github.io/fd-nls/](https://shidel.github.io/fd-nls/) Good enough for now. I'll tweak the report.sh to not stick a table in the README and add links to the html report. Only a matter of a few minutes work.

**Comment by shidel** [comment]
Looking forward to your translation how-to documentation. :-)

Thinking about it a little more... Possibly only add a note and link in the README.md. Then put everything under a contributor-howto/ directory (or maybe a-howto-contribute/ so it is right at the top). That way the root of the repo doesn't get any more cluttered. Also, if the "how-to" is provided in several languages it will be nicely contained under that directory.

**Comment by shidel** [comment]
On a side note, I'll probably end up tweaking the report.html to use the GitHub pages theme. Also, move the HTML version into the "how-to" directory.

**Comment by cardpuncher** [comment]
On 29.08.2021 21:36, shidel wrote:
> Looking forward to your translation how-to documentation. :-)

Give me a few days, I need to finish DOSLFN in French first :-)

> Thinking about it a little more... Possibly only add a note and link in
> the README.md. Then put everything under a contributor-howto/ directory
> (or maybe a-howto-contribute/ so it is right at the top). That way the
> root of the repo doesn't get any more cluttered. Also, if the "how-to"
> is provided in several languages it will be nicely contained under that
> directory.

I think it makes sense to keep the contributing how-to in English only
as that's the source language. By the way, I think I may add some
screenshots and maybe some animated gifs in the tutorial.

Also, the black themed GitHub page looks great! Thank you!
