### ISSUE TITLE
"Tee" in the language list

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#79]
This is really a minor issue, but just as a reminder I'm leaving this note here: in the language list for the tee program, there's a language called... "tee".

In [report.txt](https://github.com/shidel/fd-nls/blob/master/report.txt), one can see the following list:
<code>tee: de, en, eo, es, fr, pl, pt, sl, tr, tee? (compare manually)</code>

**Comment by shidel** [comment]
fixed
