### ISSUE TITLE
V8POWER translations not shown on report.txt

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#81]
Hi,

Just noticed that the [HTML report](https://shidel.github.io/fd-nls/report.html) and [report.txt](https://github.com/shidel/fd-nls/blob/master/report.txt) do not show anything for v8power translations. This may be related to the fix of #79.

**Comment by shidel** [comment]
Hi,

It is not related and #79 was fixed. 

They don't show up for three reasons. 

- First, they are HELP not NLS. While the report does do some stuff for help, it does not do much.
- Second, they are broken into language sub-directories. For comparison, they would all need to be just under help. 
- Third, v8power is a special multi-program suite. The report doesn't really do those. The exception to that is PGME. For that I had to make an entire sub-section that could compare the individual programs in it. That is a large undertaking and isn't really worth the effort. 

The whole report generation process needs revamped. Eventually, I'll get to it. :-)
