### ISSUE TITLE
Spanish translations of Move has odd graphic characters

### ISSUE THREAD

**Issue by andrewbird** [shidel/fd-nls#97]
The Spanish translation which is supposed to be cp850 shows graphic characters when converted to UTF-8, see below
~~~
# Mensajes varios                                                               
                                                                                
1.0:No existe                                                                   
1.1:┬¡ya esiste!                                                                
1.2:Sobreescribir fichero                                                       
1.3:Problema moviendo directorio                                                
1.4:Problema moviendo fichero                                                   
1.5:Par┬ámetro no v┬álido                                                       
1.6:Unidad origen no v┬álida                                                    
1.7:Fichero destino no v┬álido                                                  
1.8: no existe como directorio. ┬¿Crearlo?                                      
1.9:Fichero origen no v┬álido                                                   
1.10:Incapaz de crear directorio                                                
~~~

My first guess is that it's actually a UTF-8 file already, but converting to cp850 fails.
~~~
$ iconv -f utf8 -t cp850 nls/move.es.UTF-8
# Mensaje de ayuda cp850
# Basado en el archivo move.en
# Traducido por Lorenzo del Toro Saravia

0.0:Move
0.1:Mueve un fichero/directorio a otro lugar.
0.2:(C) 1997-2002 by Joe Cosentino
0.3:(C) 2003-2004 by Imre Leber
0.4:Sintaxis: MOVE
0.5:origen1[, origen2[,...]] destino
0.6: origen      El nombre del fichero o directory you want to move (rename)
0.7: destino     El lugar a donde desea mover el (los) fichero(s)
0.8:          No pide confirmaci�n para sobreescribir un fichero  
0.9:             ya existente en la ruta destino.
0.10:         Pide confirmacion antes de sobreescribir un fichero
0.11:             ya existente en la ruta destino.
0.12:          Verifica cada fichero seg�n se escribe en el destino para
0.13:             asegurarse de que los ficheros de destino so idiconv: illegal input sequence at position 793
~~~

So looking at the file it has variable length chars (just like UTF-8, not UCS2), but I don't know any further. Perhaps somebody could check it over and fix it (my Spanish is not that good yet!).

**Comment by shidel** [comment]
@andrewbird commit bd9ccaf436b47a9c8cb504b5d81959ab91ebda55 should fix the issue.

**Comment by shidel** [comment]
Hi @andrewbird,

When I fixed it, I didn't even notice. But after you mentioned it, I saw there were a couple error messages that were also still in English. Like you, I speak very very little Spanish. But with the help of Google Translate, I think it is all good now with commit 8d524f5f193c9f100d9f10720a2bd51aa3418bfb. Overall, it looks pretty good. I'm not sure about `rename = rebautizar`. But, I'm not going to worry about it. :-)

**Comment by andrewbird** [comment]
Hello @shidel,
   I've been learning Spanish via Duolingo for the past year. We didn't do it at school as French was our nominated foreign language. I'm still in the beginner phase and still have to be sure not to offend, amuse or otherwise create rubbish. Have you tried https://www.deepl.com? I find it much more predictable than Google translate, though there are less languages.
  Thanks for the updates, I'll be sure to add them in to the repo. At the moment I'm working on getting `move` buildable with tcc, watcom and gcc-ia16. Thanks to @tkchia's work providing Borland/Watcom compatible functions in his newlib and libi86 libraries I'm hoping the changes can be minimal.

Thank you!

**Comment by shidel** [comment]
@andrewbird, I took a Spanish class in high school 3 or 4 millennia ago and paid very little attention. But, I used to travel a lot and frequently came contact with individuals who spoke little or no English. Generally, that would happen when I was ordering food. But, It would come up other times as well. You can get by fairly well with only a couple words and a lot of gestures. :-) So with no effort on my part, surprisingly my Spanish has improved a little. Without really trying, I already have an OK feel for the language and syntax. So when I plug something into Google Translate and see the output, I fairly often find myself "knowing" that is not correct. At one time, I bought some audiobooks to learn Spanish. But, never bothered to listen to them. At some point, I may get around to putting some effort into actually learning the language.
